version: '3.9'

services:
  nest:
    container_name: rh-nest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:${DB_PORT}/${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_BUCKET: ${MINIO_BUCKET}
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - rh-network

  mysql:
    image: mysql:8.4.5
    container_name: rh-mysql
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - .env.development
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql/conf.cnf:/etc/mysql/conf.d/my-custom.cnf
    networks:
      - rh-network

  minio:
    image: minio/minio
    container_name: rh-minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    env_file:
      - .env.development
    volumes:
      - minio_data:/data
    networks:
      - rh-network

volumes:
  mysql_data:
  minio_data:

networks:
  rh-network:
    name: rh-network
